all : project1_1 project1_2
project1_1 : project1_1.c
	gcc project1_1.c -o project1_1

project1_2 : project1_2.c
	gcc project1_2.c -o project1_2

hello:
	echo "Hello World"
clean:
	rm -f project1_1 project1_2